#!/bin/bash
set -x

# Actualizamos la lista de paquetes
apt update

# Instalamos el MySQL Server
apt install mysql-server -y

#VARIABLES
BD_ROOT_PASSWD=root
IP_PRIVADA_FRONT=172.31.87.228
ROOT_MYSQL=pilar


# Actualizamos la contraseña de root de MySQL
mysql -u root <<< "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$BD_ROOT_PASSWD';"

# --------------------------------------------------------------------------------
# Ejecutamos el script de base de datos de la aplicación web
# --------------------------------------------------------------------------------

# Clonamos el repositorio
cd /home/ubuntu
rm -rf iaw-practica-lamp
git clone https://github.com/josejuansanchez/iaw-practica-lamp

# Importamos el script de creación de la base de datos
mysql -u root -p$BD_ROOT_PASSWD < /home/ubuntu/iaw-practica-lamp/db/database.sql

#-----------------------------------------#

#Configuramos MySQL para permitir conexiones desde la IP privada de la instancia

sudo sed -i "s/127.0.0.1/$IP_PRIVADA_FRONT/" /etc/mysql/mysql.conf.d/mysqld.cnf

#Reiniciamos servicio MySQL
/etc/init.d/mysql restart


